language: python
matrix:
  include:
  - name: "Attiny85 firmware"
    python: "2.7"
    env: PLATFORMIO_CI_SRC=./Attiny85
  - name: "ESP8266 firmware"
    python: "2.7"
    env: PLATFORMIO_CI_SRC=./ESP8266
    
git:
  depth: 3
  submodules: false

branches:
  only:
  - master
  
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio

script:
    - platformio ci --project-conf=$PLATFORMIO_CI_SRC/platformio.ini
    
notifications:
  email:
    on_success: change
    on_failure: change